runtime: python39
service: ai-model-comparison
instance_class: F1

env_variables:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
  GOOGLE_API_KEY: ${GOOGLE_API_KEY}
  OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
  EXCHANGERATE_API_KEY: ${EXCHANGERATE_API_KEY}

entrypoint: gunicorn -b :$PORT app:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10 